# Generated by Django 5.2.8 on 2025-11-28 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_book_borrowrecord_category_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 12, 5, 2, 17, 64016, tzinfo=datetime.timezone.utc)),
        ),
    ]
