# Generated by Django 5.2.8 on 2025-12-29 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 11, 19, 4, 282315, tzinfo=datetime.timezone.utc)),
        ),
    ]
