# Generated by Django 5.2.8 on 2025-12-30 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 3, 40, 12, 91525, tzinfo=datetime.timezone.utc)),
        ),
    ]
